--Use AddressBookService;
--CREATE TABLE AddressBook (FirstName VARCHAR(20),LastName VARCHAR(20),Address VARCHAR(50),City VARCHAR(20),State VARCHAR(15),Zip INTEGER,
--PhoneNo INTEGER PRIMARY KEY,Email VARCHAR(30))
